version: "3.9"
services:
  webapp:
    build:
      context: web_app/
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
    volumes:
      - ./web_app/app:/app
  backapp:
    build:
      context: back_app/
      dockerfile: Dockerfile
    volumes:
      - caddy_data:/data
      - caddy_config:/config
      - ./back_app/app:/app
    ports:
      # HTTP
      - target: 80
        published: ${HTTP_PORT:-80}
        protocol: tcp

volumes:
  webapp:
  caddy_data:
  caddy_config: