monolog:
    channels: ['deprecation']
    handlers:
        main:
            type: stream
            path: "php://stderr"
            level: debug
            channels: ["!event", "!deprecation"]
            formatter: monolog.formatter.json
        console:
            type: console
            process_psr_3_messages: false
            channels: ["!event", "!doctrine", "!console"]

when@dev:
    monolog:
        handlers:
            main:
                type: stream
                path: "php://stderr"
                level: debug
                channels: ["!event", "!deprecation"]
                formatter: monolog.formatter.json

when@test:
    monolog:
        handlers:
            main:
                type: stream
                path: "php://stderr"
                level: debug
                channels: ["!event", "!deprecation", "!doctrine"]
                formatter: monolog.formatter.json

when@prod:
    monolog:
        handlers:
            main:
                type: stream
                path: "php://stderr"
                level: info
                formatter: monolog.formatter.json
            nested:
                type: stream
                path: "php://stderr"
                level: debug
                formatter: monolog.formatter.json
            console:
                type: console
                process_psr_3_messages: false
                channels: ["!event", "!doctrine"]
            deprecation:
                type: stream
                channels: [deprecation]
                path: "php://stderr"
