name: Docker Hub Publish

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  REGISTRY: docker.io
  WEBAPP_IMAGE_NAME: rearius/tabel-web
  BACKEND_IMAGE_NAME: rearius/tabel-backend

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push WebApp image
        uses: docker/build-push-action@v4
        with:
          context: ./web_app
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.WEBAPP_IMAGE_NAME }}:latest
            ${{ env.REGISTRY }}/${{ env.WEBAPP_IMAGE_NAME }}:${{ github.sha }}

      - name: Build and push Backend image
        uses: docker/build-push-action@v4
        with:
          context: ./back_app
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.BACKEND_IMAGE_NAME }}:latest
            ${{ env.REGISTRY }}/${{ env.BACKEND_IMAGE_NAME }}:${{ github.sha }}